### ISSUE TITLE
iCOR integration - feedback needed

### ISSUE THREAD

**Issue by jarekdobrzanski** [parameterspace-ie/eo4a-service-trials#19] opened 2018-03-01 16:39 UTC
We've run a Workflow icor_test_1_Feb2018 (job 1191) and got a message that is has finished successfully. There's no processed files in output directory though. The service log only records successful installation of iCOR plugin so I'm not sure if the iCOR service command was called or not. Please provide more feedback about status of this job so we can investigate further.

**Comment by derekocallaghan** [comment] 2018-03-01 17:32
The service command was called and completed successfully. However, it is recommended that additional log messages be added to assist in debugging issues. In this case, as there is nothing in the corresponding service.log, we can only assume that the issue is a typo in line 35 of `wrapper.py` (`if '--input-dir' in sys.argv:`), as the corresponding WPS parameter name is `input_dir` according to `wps.py`.

**Comment by jarekdobrzanski** [comment] 2018-03-06 10:31
The logging is beefed up in the last update and the input_dir param is corrected. We should be able to see the all stdout and stderr from icor plugin in service log now

**Comment by derekocallaghan** [comment] 2018-03-06 14:53
Closing as the service now uses the correct parameter name

**Closed as completed by derekocallaghan** 2018-03-06 14:53 UTC
